A: !!python/tuple
- 0
- 0
B: !!python/tuple
- 4
- 4
batch: 64
collision_penalty: -80.0
delivery_reward: 120.0
device: cpu
episodes: 1500
eps_decay: 12000
eps_end: 0.05
eps_start: 0.6
gamma: 0.99
grid_size: 5
hidden: 256
joint_action_every: 50
log_every: 50
logdir: runs/phase2_dqn_safe_final
lr: 0.001
max_steps: 50
max_total_steps: 75000
n_agents: 4
phase_a_steps: 4000
pickup_reward: 1.0
replay: 30000
step_penalty: -0.01
target_update_every: 100
video_file: phase2_safe_final_demo.mp4
